const KEY='workdeskFinalV2';
const fresh=()=>({user:null,tasks:[],reminders:[],notes:[],notifications:[],activity:[],settings:{theme:'light',notifications:true,sound:true,dateFormat:'DD/MM/YYYY',timeFormat:'12'},privateUnlocked:false});
let data=load(),page='overview',cal=new Date(),timer;
function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return fresh()}}
function save(){data.privateUnlocked=false;localStorage.setItem(KEY,JSON.stringify(data))}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function esc(x=''){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function date(x){return x?new Date(x+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):''}
function dt(x){return new Date(x).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:data.settings.timeFormat==='24'?'short':'short'})}
function today(){return new Date().toISOString().slice(0,10)}
function toast(x){let t=document.getElementById('toast');t.textContent=x;t.className='toast show';setTimeout(()=>t.className='toast',2200)}
function notify(title,body){data.notifications.unshift({id:id(),title,body,time:new Date().toISOString(),read:false});data.notifications=data.notifications.slice(0,100)}
function activity(x){data.activity.unshift({text:x,time:new Date().toISOString()});data.activity=data.activity.slice(0,20)}
function unread(){return data.notifications.filter(x=>!x.read).length}
function top(){document.getElementById('profile').textContent=data.user?.username||'';document.getElementById('count').textContent=unread();document.getElementById('count').style.display=unread()?'block':'none';document.getElementById('theme').textContent=data.settings.theme==='dark'?'☀':'☾';document.body.classList.toggle('dark',data.settings.theme==='dark')}
function screen(n){['authScreen','welcomeScreen','appScreen'].forEach(x=>document.getElementById(x).classList.toggle('hidden',x!==n))}
function welcome(){document.getElementById('welcomeText').textContent='Welcome, '+data.user.username;screen('welcomeScreen');setTimeout(()=>{screen('appScreen');startTimer();go(page)},1700)}
function go(p){page=p;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===p));document.getElementById('pageTitle').textContent={overview:'Overview',tasks:'Tasks',private:'Private Tasks',reminders:'Task Reminder',notifications:'Notifications',notes:'Notes',calendar:'Calendar',settings:'Settings'}[p];render()}
function render(){top();({overview:overview,tasks:tasks,private:privatePage,reminders:reminders,notifications:notifications,notes:notes,calendar:calendarPage,settings:settings}[page])(document.getElementById('content'))}
function modal(title,body){document.getElementById('modal').innerHTML='<div class="modal-bg" id="mb"><div class="modal-box"><h3>'+title+'</h3>'+body+'</div></div>'}
function closeModal(){document.getElementById('modal').innerHTML=''}
function taskHTML(a,compact=false){return a.map(t=>`<div class="task ${t.done?'done':''}"><input type="checkbox" ${t.done?'checked':''} onchange="toggleTask('${t.id}')"><div><div class="title">${esc(t.title)}</div><div class="muted">${esc(t.description||'')}</div><div class="meta"><span class="pill ${t.priority}">${esc(t.priority)}</span>${t.category?`<span class="pill">${esc(t.category)}</span>`:''}${t.due?`<span class="pill">Due ${date(t.due)}</span>`:''}${t.private?'<span class="pill">🔒 Private</span>':''}</div></div>${compact?'':'<div class="task-actions"><button onclick="editTask(\''+t.id+'\')">Edit</button><button onclick="deleteTask(\''+t.id+'\')">Delete</button></div>'}</div>`).join('')}
function overview(c){let p=data.tasks.filter(t=>!t.private&&!t.done).length,d=data.tasks.filter(t=>!t.private&&t.done).length,r=data.reminders.filter(x=>new Date(x.when)>=new Date()).length;c.innerHTML=`<div class="grid stats"><div class="card stat"><span>Pending Tasks</span><strong>${p}</strong></div><div class="card stat"><span>Completed Tasks</span><strong>${d}</strong></div><div class="card stat"><span>Upcoming Reminders</span><strong>${r}</strong></div><div class="card stat"><span>Unread Notifications</span><strong>${unread()}</strong></div></div><div class="grid two" style="margin-top:17px"><section class="panel"><h3>Today's Tasks</h3>${taskHTML(data.tasks.filter(t=>!t.private&&t.due===today()),true)||'<div class="muted">No tasks for today.</div>'}</section><section class="panel"><h3>Recent Activity</h3>${data.activity.slice(0,7).map(a=>`<p class="muted">${esc(a.text)}<br><small>${dt(a.time)}</small></p>`).join('')||'<div class="muted">No recent activity.</div>'}</section></div>`}
function tasks(c){c.innerHTML=`<div class="toolbar"><div><button class="primary" onclick="openTask()">+ New Task</button> <input id="tq" placeholder="Search tasks..." oninput="filterTasks()"><select id="ts" onchange="filterTasks()"><option value="all">All status</option><option value="pending">Pending</option><option value="done">Completed</option></select></div></div><div id="taskList" class="task-list"></div>`;filterTasks()}
function filterTasks(){let q=(document.getElementById('tq')?.value||'').toLowerCase(),s=document.getElementById('ts')?.value||'all';let a=data.tasks.filter(t=>!t.private&&(t.title+' '+t.description+' '+t.category).toLowerCase().includes(q)&&(s==='all'||(s==='done'?t.done:!t.done)));document.getElementById('taskList').innerHTML=taskHTML(a)||'<div class="muted">No matching tasks.</div>'}
function openTask(t=null,due=''){modal(t?'Edit Task':'Create Task',`<form id="tf"><div class="field"><label>Task name</label><input id="ft" required value="${esc(t?.title||'')}"></div><div class="field"><label>Description</label><textarea id="fd" rows="4">${esc(t?.description||'')}</textarea></div><div class="grid" style="grid-template-columns:1fr 1fr"><div class="field"><label>Due date</label><input id="fdate" type="date" value="${t?.due||due}"></div><div class="field"><label>Priority</label><select id="fp"><option value="high" ${t?.priority==='high'?'selected':''}>High</option><option value="medium" ${!t||t.priority==='medium'?'selected':''}>Medium</option><option value="low" ${t?.priority==='low'?'selected':''}>Low</option></select></div></div><div class="field"><label>Category</label><input id="fc" value="${esc(t?.category||'')}" placeholder="Personal, Work, Study..."></div><label><input id="fprivate" type="checkbox" ${t?.private?'checked':''}> Mark as Private</label><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>`);document.getElementById('tf').onsubmit=e=>{e.preventDefault();let o={id:t?.id||id(),title:ft.value.trim(),description:fd.value.trim(),due:fdate.value,priority:fp.value,category:fc.value.trim(),private:fprivate.checked,done:t?.done||false};if(t)Object.assign(t,o);else data.tasks.unshift(o);activity(t?'Task updated':'Task created');save();closeModal();render();toast('Task saved')}}
function toggleTask(i){let t=data.tasks.find(x=>x.id===i);t.done=!t.done;activity((t.done?'Completed: ':'Reopened: ')+t.title);save();render()}
function editTask(i){let t=data.tasks.find(x=>x.id===i);openTask(t)}
function deleteTask(i){if(confirm('Delete this task?')){data.tasks=data.tasks.filter(x=>x.id!==i);save();render();toast('Task deleted')}}
function unlock(cb){if(data.privateUnlocked){cb();return}if(!data.user.pin){toast('Set a Private PIN in Settings first');go('settings');return}modal('Unlock Private Tasks',`<div class="lock"><div class="big">🔒</div><p>Enter your Private PIN.</p><div class="field"><input id="pin" type="password" inputmode="numeric"></div><button class="primary" id="ub">Unlock</button></div>`);ub.onclick=()=>{if(pin.value!==data.user.pin){toast('Incorrect PIN');return}data.privateUnlocked=true;closeModal();cb();render()}}
function privatePage(c){if(!data.privateUnlocked){c.innerHTML='<section class="panel lock"><div class="big">🔒</div><h3>Private Tasks are Locked</h3><p class="muted">Private tasks are hidden from normal tasks, dashboard, search and calendar.</p><button class="primary" onclick="unlock(()=>render())">Unlock Private Tasks</button></section>';return}c.innerHTML=`<div class="toolbar"><button class="primary" onclick="openTask()">+ New Private Task</button><button class="secondary" onclick="lockPrivate()">Lock Now</button></div><div class="task-list">${taskHTML(data.tasks.filter(t=>t.private))||'<div class="muted">No private tasks.</div>'}</div>`}
function lockPrivate(){data.privateUnlocked=false;render();toast('Private Tasks locked')}
function reminders(c){c.innerHTML=`<div class="toolbar"><button class="primary" onclick="openReminder()">+ New Reminder</button></div><div class="rem-list">${data.reminders.sort((a,b)=>new Date(a.when)-new Date(b.when)).map(r=>`<div class="card"><strong>${r.private?'🔒 Private task reminder':esc(r.title)}</strong><p class="muted">${dt(r.when)}</p><button class="secondary" onclick="editReminder('${r.id}')">Edit</button> <button class="danger" onclick="deleteReminder('${r.id}')">Delete</button></div>`).join('')||'<div class="muted">No reminders.</div>'}</div>`}
function openReminder(r=null){modal(r?'Edit Reminder':'Create Reminder',`<form id="rf"><div class="field"><label>Reminder title</label><input id="rt" required value="${esc(r?.title||'')}"></div><div class="grid" style="grid-template-columns:1fr 1fr"><div class="field"><label>Date</label><input id="rd" type="date" required value="${r?new Date(r.when).toISOString().slice(0,10):today()}"></div><div class="field"><label>Time</label><input id="rm" type="time" required value="${r?new Date(r.when).toTimeString().slice(0,5):'09:00'}"></div></div><label><input id="rp" type="checkbox" ${r?.private?'checked':''}> Private reminder</label><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>`);rf.onsubmit=e=>{e.preventDefault();let o={id:r?.id||id(),title:rt.value.trim(),when:new Date(rd.value+'T'+rm.value).toISOString(),private:rp.checked,fired:r?.fired||false};if(r)Object.assign(r,o);else data.reminders.push(o);save();closeModal();render();toast('Reminder saved')}}
function editReminder(i){openReminder(data.reminders.find(x=>x.id===i))}function deleteReminder(i){if(confirm('Delete this reminder?')){data.reminders=data.reminders.filter(x=>x.id!==i);save();render()}}
function startTimer(){clearInterval(timer);timer=setInterval(check,15000);check()}
function check(){let changed=false;data.reminders.forEach(r=>{if(!r.fired&&new Date(r.when)<=new Date()){r.fired=true;notify(r.private?'Private task reminder':r.title,r.private?'A private reminder is due.':'Your reminder is due: '+r.title);changed=true;if(data.settings.sound)beep()}});if(changed){save();top();if(page==='notifications')render()}}
function beep(){try{let A=AudioContext||webkitAudioContext,a=new A,o=a.createOscillator,g=a.createGain;o.connect(g);g.connect(a.destination);o.frequency.value=740;g.gain.value=.06;o.start();o.stop(a.currentTime+.25)}catch{}}
function notifications(c){c.innerHTML=`<div class="toolbar"><button class="secondary" onclick="readAll()">Mark all as read</button></div><section class="panel">${data.notifications.map(n=>`<div class="notification ${n.read?'':'unread'}"><strong>${esc(n.title)}</strong><div>${esc(n.body)}</div><small class="muted">${dt(n.time)}</small></div>`).join('')||'<div class="muted">No notifications.</div>'}</section>`}
function readAll(){data.notifications.forEach(n=>n.read=true);save();render()}
function notes(c){c.innerHTML=`<div class="toolbar"><button class="primary" onclick="openNote()">+ New Note</button><input id="nq" placeholder="Search notes..." oninput="filterNotes()"></div><div id="noteList" class="grid note-grid"></div>`;filterNotes()}
function filterNotes(){let q=(document.getElementById('nq')?.value||'').toLowerCase();document.getElementById('noteList').innerHTML=data.notes.filter(n=>(n.title+' '+n.body).toLowerCase().includes(q)&&(!n.private||data.privateUnlocked)).map(n=>`<article class="card note"><h4>${n.private?'🔒 ':''}${esc(n.title)}</h4><div>${esc(n.body).slice(0,250)}</div><p><button class="secondary" onclick="editNote('${n.id}')">Edit</button> <button class="danger" onclick="deleteNote('${n.id}')">Delete</button></p></article>`).join('')||'<div class="muted">No notes found.</div>'}
function openNote(n=null){if(n?.private&&!data.privateUnlocked){unlock(()=>openNote(n));return}modal(n?'Edit Note':'Create Note',`<form id="nf"><div class="field"><label>Title</label><input id="nt" required value="${esc(n?.title||'')}"></div><div class="field"><label>Note</label><textarea id="nb" rows="8">${esc(n?.body||'')}</textarea></div><label><input id="np" type="checkbox" ${n?.private?'checked':''}> Private note</label><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>`);nf.onsubmit=e=>{e.preventDefault();let o={id:n?.id||id(),title:nt.value.trim(),body:nb.value,private:np.checked};if(n)Object.assign(n,o);else data.notes.unshift(o);save();closeModal();render();toast('Note saved')}}
function editNote(i){openNote(data.notes.find(x=>x.id===i))}function deleteNote(i){let n=data.notes.find(x=>x.id===i);if(n.private&&!data.privateUnlocked){unlock(()=>deleteNote(i));return}if(confirm('Delete this note?')){data.notes=data.notes.filter(x=>x.id!==i);save();render()}}
function calendarPage(c){let y=cal.getFullYear(),m=cal.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate(),cells=[];for(let i=0;i<42;i++){let d=i-start+1,yy=y,mm=m;if(d<1){d=prev+d;mm--;if(mm<0){mm=11;yy--}}else if(d>days){d-=days;mm++;if(mm>11){mm=0;yy++}}let ds=`${yy}-${String(mm+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,muted=mm!==m,ev=data.tasks.filter(t=>!t.private&&t.due===ds).slice(0,3).map(t=>`<div class="event">${esc(t.title)}</div>`).join('')+data.reminders.filter(r=>!r.private&&r.when.slice(0,10)===ds).slice(0,2).map(r=>`<div class="event">⏰ ${esc(r.title)}</div>`).join('');cells.push(`<div class="day ${muted?'muted':''} ${ds===today()?'today':''}" ${muted?'':'onclick="openTask(null,\''+ds+'\')"'}><b>${d}</b>${ev}</div>`)}c.innerHTML=`<section class="panel"><div class="toolbar"><div><button class="secondary" onclick="moveMonth(-1)">‹</button><select onchange="cal.setMonth(+this.value);render()">${Array.from({length:12},(_,i)=>`<option value="${i}" ${i===m?'selected':''}>${new Date(2000,i).toLocaleString('en',{month:'long'})}</option>`).join('')}</select><select onchange="cal.setFullYear(+this.value);render()">${Array.from({length:31},(_,i)=>`<option ${2020+i===y?'selected':''}>${2020+i}</option>`).join('')}</select><button class="secondary" onclick="moveMonth(1)">›</button></div><button class="secondary" onclick="cal=new Date();render()">Today</button></div><div class="calendar">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="weekday">${x}</div>`).join('')}${cells.join('')}</div></section>`}
function moveMonth(n){cal.setMonth(cal.getMonth()+n);render()}
function settings(c){c.innerHTML=`<div class="grid settings"><section class="setting"><h3>Profile</h3><div class="field"><label>Name / Username</label><input id="pn" value="${esc(data.user.username)}"></div><div class="field"><label>Email (optional)</label><input id="pe" value="${esc(data.user.email||'')}"></div><div class="field"><label>Bio / Status (optional)</label><textarea id="pb">${esc(data.user.bio||'')}</textarea></div><button class="primary" onclick="saveProfile()">Save Profile</button></section><section class="setting"><h3>Security</h3><p class="muted">Set a separate PIN to protect Private Tasks and Private Notes.</p><div class="field"><label>Private PIN</label><input id="pp" type="password" inputmode="numeric" placeholder="4-12 digits"></div><button class="primary" onclick="savePin()">Save PIN</button><hr><div class="field"><label>New password</label><input id="newpass" type="password"></div><button class="secondary" onclick="changePass()">Change Password</button></section><section class="setting"><h3>Appearance</h3><button class="secondary" onclick="toggleTheme()">Switch to ${data.settings.theme==='dark'?'Light':'Dark'} mode</button><h3>Notifications</h3><label><input type="checkbox" ${data.settings.notifications?'checked':''} onchange="data.settings.notifications=this.checked;save()"> Enable notifications</label><br><label><input type="checkbox" ${data.settings.sound?'checked':''} onchange="data.settings.sound=this.checked;save()"> Reminder sound</label></section><section class="setting"><h3>General</h3><div class="field"><label>Date format</label><select onchange="data.settings.dateFormat=this.value;save()"><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option></select></div><div class="field"><label>Time format</label><select onchange="data.settings.timeFormat=this.value;save()"><option value="12">12-hour</option><option value="24">24-hour</option></select></div></section></div>`}
function saveProfile(){data.user.username=pn.value.trim()||data.user.username;data.user.email=pe.value.trim();data.user.bio=pb.value.trim();save();top();toast('Profile updated')}
function savePin(){if(!/^\d{4,12}$/.test(pp.value)){toast('PIN must be 4-12 digits');return}data.user.pin=pp.value;save();toast('Private PIN saved')}
function changePass(){if(newpass.value.length<4){toast('Password must be at least 4 characters');return}data.user.password=newpass.value;save();toast('Password changed')}
function toggleTheme(){data.settings.theme=data.settings.theme==='dark'?'light':'dark';save();render()}
function searchAll(){let q=search.value.trim().toLowerCase();if(!q){results.classList.add('hidden');return}let a=[];data.tasks.filter(t=>!t.private).forEach(t=>{if((t.title+' '+t.description).toLowerCase().includes(q))a.push(['Task',t.title,t.due?'Due '+date(t.due):''])});data.notes.filter(n=>!n.private).forEach(n=>{if((n.title+' '+n.body).toLowerCase().includes(q))a.push(['Note',n.title,n.body.slice(0,70)])});data.reminders.filter(r=>!r.private).forEach(r=>{if(r.title.toLowerCase().includes(q))a.push(['Reminder',r.title,dt(r.when)])});results.innerHTML=a.slice(0,12).map(x=>`<div class="result"><strong>${esc(x[1])}</strong><small>${x[0]} · ${esc(x[2])}</small></div>`).join('')||'<div class="result"><small>No matching WorkDesk items.</small></div>';results.classList.remove('hidden')}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');loginForm.classList.toggle('hidden',b.dataset.auth!=='login');registerForm.classList.toggle('hidden',b.dataset.auth!=='register')});
document.querySelectorAll('.show').forEach(b=>b.onclick=()=>{let i=document.getElementById(b.dataset.target);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Show':'Hide'});
loginForm.onsubmit=e=>{e.preventDefault();if(!data.user||loginUser.value.trim()!==data.user.username||loginPassword.value!==data.user.password){loginError.textContent='Incorrect User ID or password.';return}welcome()};
registerForm.onsubmit=e=>{e.preventDefault();if(regUser.value.trim().length<3){registerError.textContent='Username must be at least 3 characters.';return}if(regPassword.value.length<4){registerError.textContent='Password must be at least 4 characters.';return}if(regPassword.value!==regConfirm.value){registerError.textContent='Passwords do not match.';return}data.user={username:regUser.value.trim(),password:regPassword.value,pin:null};save();loginUser.value=data.user.username;registerError.textContent='';document.querySelector('[data-auth="login"]').click();toast('Account created')};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.page));
logout.onclick=()=>{data.privateUnlocked=false;save();screen('authScreen');toast('Logged out')};
theme.onclick=toggleTheme;bell.onclick=()=>go('notifications');profile.onclick=()=>go('settings');search.oninput=searchAll;document.addEventListener('click',e=>{if(!e.target.closest('.search'))results.classList.add('hidden')});
window.openTask=openTask;window.toggleTask=toggleTask;window.editTask=editTask;window.deleteTask=deleteTask;window.unlock=unlock;window.lockPrivate=lockPrivate;window.openReminder=openReminder;window.editReminder=editReminder;window.deleteReminder=deleteReminder;window.readAll=readAll;window.openNote=openNote;window.editNote=editNote;window.deleteNote=deleteNote;window.moveMonth=moveMonth;window.saveProfile=saveProfile;window.savePin=savePin;window.changePass=changePass;window.toggleTheme=toggleTheme;
if(data.user)welcome();else screen('authScreen');
